### ISSUE TITLE
fails to compile on mac

### ISSUE THREAD

**Issue by egaburov** [jaredhoberock/agency#136]
I tried master branch on Mac (saxpy.cu repro form https://github.com/jaredhoberock/agency/issues/134) , and get compilation error:

    $ nvcc saxpy.cu -I.  -std=c++11 -run
    ./agency/cuda/future.hpp:256:40: error: no member named 'when_all_events_are_ready' in namespace 'agency::cuda::detail'
    detail::event when_all_ready = detail::when_all_events_are_ready((futures.event())...);
                                   ~~~~~~~~^
    ./agency/cuda/detail/when_all_execute_and_select.hpp:285:32: error: no member named 'when_all_events_are_ready' in namespace
          'agency::cuda::detail'
    event when_all_ready = detail::when_all_events_are_ready(gpu, (outer_arg_future.event()), (agency::detail::get< TupleIndices> (tuple_of_fu...
                           ~~~~~~~~^
    2 errors generated.

    $ nvcc --version
    nvcc: NVIDIA (R) Cuda compiler driver
    Copyright (c) 2005-2015 NVIDIA Corporation
    Built on Sat_Jan__2_22:14:02_CST_2016
    Cuda compilation tools, release 8.0, V8.0.7

    $ git bisect
    ...
    3370470e39cb7575093fb1fe27b77212f0b0d087 is the first bad commit
    commit 3370470e39cb7575093fb1fe27b77212f0b0d087
    Author: Jared Hoberock <jaredhoberock@gmail.com>
    Date:   Tue Nov 3 15:20:01 2015 -0800
    
        Implement when_all() for cuda::detail::event

    :040000 040000 18274f62bd47f93f36e2897b4caa7038b0753505 573afd0a3f43155ee2119cbc313416f41eb2b989 M      agency

**Comment by jaredhoberock** [comment]
Thanks @egaburov, could you confirm whether or not [this branch](https://github.com/jaredhoberock/agency/tree/issue-136) eliminates this particular compiler error?

**Comment by egaburov** [comment]
Compiler error is gone. Code builds & runs. I am not sure I understand what exactly the problem is with clang here.. Can you explain in few words? Thanks.

**Comment by jaredhoberock** [comment]
Thanks. `g++` and `clang` disagree about which namespace the friend function `when_all_events_are_ready()` belongs to when it is defined inside the class rather than outside the class. I don't know which interpretation is correct.
